matière_1 = float(input('Entrer la 1ere note : '))
matière_2 = float(input('Entrer la 2eme note : '))
matière_3 = float(input('Entrer la 3eme note : '))
matière_4 = float(input('Entrer la 4eme note : '))
matière_5 = float(input('Entrer la 5eme note : '))
total = matière_1 + matière_2 + matière_3 + matière_4 + matière_5
moyenne = total / 5.0
pourcentage = (moyenne * 100) / 20
print("Total = ", total)
print("Moyenne = ", moyenne)
print("Pourcentage = ", pourcentage,"%")
